const declarations = {
  'container': { 'margin': '0 auto', 'max-width': '1170px', 'selector': '.container' },
  'section': { 'display': 'flex', 'selector': 'section' },
  'flex': { 'display': 'flex', 'selector': '.flex'},
  'flexColumn': { 'flex-direction': 'column', 'selector': '.flex-column' },
  'flexOne': { 'flex': '1', 'selector': '.flex-one' },
  'alignCenter': { 'align-items': 'center', 'selector': '.align-center' },
  'center': { 'justify-content': 'center', 'selector': '.center' },
  'spaceBetween': { 'justify-content': 'space-between', 'selector': '.space-between' },
  'btn': { 'cursor': 'pointer', 'border': '0', 'padding': '6px 12px', 'line-height': '1.4', 'border-radius': '3px', 'selector': '.btn' },
  'btnDefault': { 'color': '#ffffff', 'background-color': '#faa541', 'selector': '.btn-default' },
  'btnPrimary': { 'color': '#ffffff', 'background-color': '#364147', 'selector': '.btn-primary' },
  'formControl': { 'display': 'block', 'padding': '6px 12px', 'border': '1px solid #a0a0a0', 'color': '#8598a2', 'line-height': '1.4', 'selector': '.form-control' },
  'textLight': { 'font-size': '30px', 'color': '#a0a0a0', 'selector': '.text-light' },
  'textSecondary': { 'font-size': '30px', 'color': '#faa541', 'selector': '.text-secondary' },
  'textPrimary': { 'font-size': '16px', 'color': '#364147', 'selector': '.text-primary' },
  'headerNav': { 'border-bottom': '1px solid #a0a0a0', 'selector': '.header-nav' },
  'brand': { 'width': '170px', 'height': '85px', 'margin-left': '-15px', 'margin-right': '60px', 'selector': '.brand' },
  'logo': { 'max-width': '100%', 'height': 'auto', 'selector': '.logo' },
  'searchBox': { 'width': '330px', 'height': '30px', 'padding': '6px 12px', 'border': '1px solid #a0a0a0', 'selector': '.search-box' },
  'searchButton': { 'background-color': '#a0a0a0', 'width': '100px', 'height': '30px', 'color': '#ffffff', 'border': '0', 'padding': '0', 'selector': '.search-button' },
  'navList': { 'padding-left': '0', 'width': '575px', 'margin-top': '10px', 'selector': '.nav-list' },
  'navListLinks': { 'font-size': '16px', 'text-transform': 'uppercase', 'font-weight': '700', 'letter-spacing': '0.2px', 'selector': '.nav-list li a' },
  'profile': { 'margin-left': 'auto', 'selector': '.profile' },
  'account': { 'text-align': 'right', 'padding': '15px', 'font-size': '18px', 'color': '#364147', 'selector': '.account' },
  'accountLinks': {'font-size': '14px', 'selector': '.account a' },
  'profilePic': { 'width': '60px', 'height': '60px', 'selector': '.profile-pic' },
  'profilePicImage': { 'border-radius': '100px', 'max-width': '100%', 'selector': '.profile-pic img' },
  'hero': { 'background-image': 'url(\'../img/hero.jpg\')', 'height': '400px', 'background-size': 'cover', 'background-position': 'center center', 'text-transform': 'uppercase', 'selector': '.hero' },
  'heroH1': { 'position': 'relative', 'left': '-30px', 'selector': '.hero h1' },
  'heroH2': { 'color': '#faa541', 'selector': '.hero h2' },
  'heroHeaders': { 'font-size': '63px', 'font-weight': '700', 'line-height': '0.9', 'selector': '.hero h1, .hero h2' },
  'heroParagraph': { 'letter-spacing': '2px', 'font-weight': '700', 'font-size': '21px', 'margin': '0 0 10px', 'selector': '.hero p' },
  'banner': { 'margin': '55px 15px', 'width': '100%', 'border-top': '1px solid #a0a0a0', 'border-bottom': '1px solid #a0a0a0', 'padding': '25px 0', 'selector': '.banner' },
  'bannerImage': { 'width': '250px', 'selector': '.banner img' },
  'bannerText': { 'font-size': '30px', 'font-weight': '700', 'text-transform': 'uppercase', 'line-height': '1', 'text-align': 'center', 'selector': '.banner-text' },
  'bannerTextLastChild': { 'font-size': '16px', 'font-weight': '400', 'margin-top': '5px', 'selector': '.banner-text > div:last-child' },
  'category': { 'flex': '0 0 25%', 'padding': '0 15px', 'selector': '.category' },
  'categoryImage': { 'width': '100%', 'selector': '.category img' },
  'categoryText': { 'color': '#364147', 'padding': '30px 0', 'text-transform': 'uppercase', 'text-align': 'center', 'selector': '.category-text' },
  'categoryTextDiv': { 'font-size': '16px', 'font-weight': '200', 'color': '#faa541', 'selector': '.category-text > div' },
  'categoryTextH3': { 'font-size': '30px', 'font-weight': '700', 'line-height': '1', 'selector': '.category-text h3' },
  'fullBanner': { 'padding': '0 15px', 'margin': '50px 0', 'position': 'relative', 'selector': '.full-banner' },
  'fullBannerBefore': { 'content': '""', 'position': 'absolute', 'border': '1px solid #ffffff', 'top': '30px', 'bottom': '30px', 'left': '50px', 'right': '50px', 'z-index': '1', 'selector': '.full-banner:before' },
  'fullBannerImage': { 'flex': '0 0 58.333333%', 'background-image': 'url(\'../img/vista.jpg\')', 'background-size': 'cover', 'background-position': 'top center', 'min-height': '400px', 'selector': '.full-banner-image' },
  'fullBannerSidebar': { 'flex': '0 0 41.666667%', 'background-color': '#364147', 'text-transform': 'uppercase', 'padding': '30px', 'color': '#ffffff', 'selector': '.full-banner-sidebar' },
  'fullBannerSidebarH4': { 'font-size': '40px', 'font-weight': '700', 'color': '#637f94', 'font-style': 'italic', 'line-height': '1', 'selector': '.full-banner-sidebar h4' },
  'fullBannerSidebarH4After': { 'content': '""', 'width': '100px', 'height': '1px', 'background-color': '#faa541', 'margin': '20px auto', 'display': 'block', 'selector': '.full-banner-sidebar h4:after' },
  'fullBannerSidebarFirst': { 'font-size': '60px', 'font-weight': '700', 'line-height': '1', 'selector': '.full-banner-sidebar > div:nth-of-type(1)' },
  'fullBannerSidebarSecond': { 'font-size': '25px', 'font-weight': '200', 'letter-spacing': '3px', 'selector': '.full-banner-sidebar > div:nth-of-type(2)' },
  'fullBannerSidebarButton': { 'margin-top': '50px', 'text-transform': 'uppercase', 'letter-spacing': '1px', 'z-index': '1', 'selector': '.full-banner-sidebar .btn.btn-default' },
  'footer': { 'display': 'flex', 'flex-wrap': 'wrap', 'position': 'relative', 'background-color': '#000000', 'min-height': '330px', 'z-index': '0', 'selector': 'footer' },
  'footerAfter': { 'content': '""', 'background-color': '#a0a0a0', 'width': '75%', 'position': 'absolute', 'top': '0', 'left': '0', 'right': '0', 'bottom': '0', 'z-index': '-1', 'selector': 'footer:after' },
  'lists': { 'flex': '0 0 75%', 'padding': '40px 15px', 'selector': '.lists' },
  'linkHeader': { 'text-transform': 'uppercase', 'font-weight': '700', 'font-size': '16px', 'margin-bottom': '15px', 'selector': '.link-header' },
  'footerLinks': { 'color': '#ffffff', 'text-transform': 'uppercase', 'font-size': '12px', 'padding': '0 0 4px', 'selector': 'footer a' },
  'footerLinksHover': { 'text-decoration': 'underline', 'selector': 'footer a:hover' },
  'socialLists': { 'display': 'inline-block', 'selector': '.social ul li' },
  'socialListsLinks': { 'display': 'block', 'width': '23px', 'height': '23px', 'background-size': '23px 23px', 'background-position': 'center', 'selector': '.social ul li a' },
  'twitter': { 'background-image': 'url(\'../img/twitter.svg\')', 'selector': '.twitter' },
  'facebook': { 'background-image': 'url(\'../img/facebook.svg\')', 'selector': '.facebook' },
  'instagram': { 'background-image': 'url(\'../img/instagram.svg\')', 'selector': '.instagram' },
  'pinterest': { 'background-image': 'url(\'../img/pinterest.svg\')', 'selector': '.pinterest' },
  'newsletterLinkHeader': { 'font-size': '12px', 'font-weight': '400', 'margin-bottom': '5px', 'selector': '.newsletter .link-header' },
  'newsletterLinkSubheader': { 'font-style': 'italic', 'font-size': '12px', 'font-weight': '400', 'margin-bottom': '15px', 'selector': '.newsletter .link-subheader' },
  'newsletterInput': { 'border': '1px solid #364147', 'width': '200px', 'margin-bottom': '10px', 'selector': '.newsletter input' },
  'newsletterButton': { 'width': '150px', 'min-width': 'auto', 'text-transform': 'uppercase', 'letter-spacing': '1px', 'selector': '.newsletter button' },
  'ps': { 'padding': '40px 0', 'color': '#e5e5e5', 'font-size': '16px', 'flex': '0 0 25%', 'selector': '.ps' },
  'psImage': { 'max-width': '230px', 'selector': '.ps img' },
  'demo': { 'padding': '0 30px', 'selector': '.demo' },
  'demoBefore': { 'content': '""', 'display': 'block', 'width': '100%', 'height': '1px', 'margin': '30px 0', 'background': 'linear-gradient(to right,#f05a28 0,#e80a89 100%)', 'selector': '.demo:before' },
  'copyright': { 'text-align': 'center', 'font-size': '12px', 'flex': '0 0 75%', 'padding': '10px 0', 'selector': '.copyright' }
}

module.exports = {
  declarations,
  container: diffAny(declarations.container, '`container`'),
  section: diffAny(declarations.section, '`section`', ['.flex']),
  flex: diffAny(declarations.flex, '`flex`', ['section']),
  flexColumn: diffAny(declarations.flexColumn, '`flexColumn`'),
  flexOne: diffAny(declarations.flexOne, '`flexOne`'),
  alignCenter: diffAny(declarations.alignCenter, '`alignCenter`'),
  center: diffAny(declarations.center, '`center`'),
  spaceBetween: diffAny(declarations.spaceBetween, '`spaceBetween`'),
  btn: diffAny(declarations.btn, '`btn`'),
  btnDefault: diffAny(declarations.btnDefault, '`btnDefault`'),
  btnPrimary: diffAny(declarations.btnPrimary, '`btnPrimary`'),
  formControl: diffAny(declarations.formControl, '`formControl`'),
  textLight: diffAny(declarations.textLight, '`textLight`'),
  textSecondary: diffAny(declarations.textSecondary, '`textSecondary`'),
  textPrimary: diffAny(declarations.textPrimary, '`textPrimary`'),
  headerNav: diffAny(declarations.headerNav, '`headerNav`'),
  brand: diffAny(declarations.brand, '`brand`'),
  logo: diffAny(declarations.logo, '`logo`'),
  searchBox: diffAny(declarations.searchBox, '`searchBox`'),
  searchButton: diffAny(declarations.searchButton, '`searchButton`'),
  navList: diffAny(declarations.navList, '`navList`'),
  navListLinks: diffAny(declarations.navListLinks, '`navListLinks`'),
  profile: diffAny(declarations.profile, '`profile`'),
  account: diffAny(declarations.account, '`account`'),
  accountLinks: diffAny(declarations.accountLinks, '`accountLinks`'),
  profilePic: diffAny(declarations.profilePic, '`profilePic`'),
  profilePicImage: diffAny(declarations.profilePicImage, '`profilePicImage`'),
  hero: diffAny(declarations.hero, '`hero`'),
  heroH1: diffAny(declarations.heroH1, '`heroH1`'),
  heroH2: diffAny(declarations.heroH2, '`heroH2`'),
  heroHeaders: diffAny(declarations.heroHeaders, '`heroHeaders`'),
  heroParagraph: diffAny(declarations.heroParagraph, '`heroParagraph`'),
  banner: diffAny(declarations.banner, '`banner`'),
  bannerImage: diffAny(declarations.bannerImage, '`bannerImage`'),
  bannerText: diffAny(declarations.bannerText, '`bannerText`'),
  bannerTextLastChild: diffAny(declarations.bannerTextLastChild, '`bannerTextLastChild`'),
  category: diffAny(declarations.category, '`category`'),
  categoryImage: diffAny(declarations.categoryImage, '`categoryImage`'),
  categoryText: diffAny(declarations.categoryText, '`categoryText`'),
  categoryTextDiv: diffAny(declarations.categoryTextDiv, '`categoryTextDiv`'),
  categoryTextH3: diffAny(declarations.categoryTextH3, '`categoryTextH3`'),
  fullBanner: diffAny(declarations.fullBanner, '`fullBanner`'),
  fullBannerBefore: diffAny(declarations.fullBannerBefore, '`fullBannerBefore`'),
  fullBannerImage: diffAny(declarations.fullBannerImage, '`fullBannerImage`'),
  fullBannerSidebar: diffAny(declarations.fullBannerSidebar, '`fullBannerSidebar`'),
  fullBannerSidebarH4: diffAny(declarations.fullBannerSidebarH4, '`fullBannerSidebarH4`'),
  fullBannerSidebarH4After: diffAny(declarations.fullBannerSidebarH4After, '`fullBannerSidebarH4After`'),
  fullBannerSidebarFirst: diffAny(declarations.fullBannerSidebarFirst, '`fullBannerSidebarFirst`'),
  fullBannerSidebarSecond: diffAny(declarations.fullBannerSidebarSecond, '`fullBannerSidebarSecond`'),
  fullBannerSidebarButton: diffAny(declarations.fullBannerSidebarButton, '`fullBannerSidebarButton`'),
  footer: diffAny(declarations.footer, '`footer`'),
  footerAfter: diffAny(declarations.footerAfter, '`footerAfter`'),
  lists: diffAny(declarations.lists, '`lists`'),
  linkHeader: diffAny(declarations.linkHeader, '`linkHeader`'),
  footerLinks: diffAny(declarations.footerLinks, '`footerLinks`'),
  footerLinksHover: diffAny(declarations.footerLinksHover, '`footerLinksHover`'),
  socialLists: diffAny(declarations.socialLists, '`socialLists`'),
  socialListsLinks: diffAny(declarations.socialListsLinks, '`socialListsLinks`'),
  twitter: diffAny(declarations.twitter, '`twitter`'),
  facebook: diffAny(declarations.facebook, '`facebook`'),
  instagram: diffAny(declarations.instagram, '`instagram`'),
  pinterest: diffAny(declarations.pinterest, '`pinterest`'),
  newsletterLinkHeader: diffAny(declarations.newsletterLinkHeader, '`newsletterLinkHeader`'),
  newsletterLinkSubheader: diffAny(declarations.newsletterLinkSubheader, '`newsletterLinkSubheader`'),
  newsletterInput: diffAny(declarations.newsletterInput, '`newsletterInput`'),
  newsletterButton: diffAny(declarations.newsletterButton, '`newsletterButton`'),
  ps: diffAny(declarations.ps, '`ps`'),
  psImage: diffAny(declarations.psImage, '`psImage`'),
  demo: diffAny(declarations.demo, '`demo`'),
  demoBefore: diffAny(declarations.demoBefore, '`demoBefore`'),
  copyright: diffAny(declarations.copyright, '`copyright`')
}